import type { EventContext, GameEvent } from '../engine/events';

/** Storylines: one choice sets a flag, and days later the story continues. */

const has = (c: EventContext, f: string) => c.flags?.[f] !== undefined;
/** Days since a flag was set (-1 if never). */
const since = (c: EventContext, f: string) => (has(c, f) ? c.day - c.flags![f] : -1);
const anyOf = (c: EventContext, ...fs: string[]) => fs.some((f) => has(c, f));
const free = (c: EventContext) => c.place !== 'home' || c.hour >= 7;

export const STORIES: GameEvent[] = [
  // ---------------- Chinedu borrows money ----------------
  {
    id: 'chinedu-borrow',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '📞',
    title: 'Chinedu dey call',
    text: '"Guy, abeg I need ₦20k urgent. Salary delay. I go pay you back Friday, I swear."',
    trigger: 'idle',
    weight: 4,
    cooldownHours: 9999,
    when: (c) => !!c.met?.includes('chinedu') && c.day >= 3 && free(c) && !anyOf(c, 'lent-chinedu', 'chinedu-done'),
    choices: [
      { label: 'Send am ₦20,000', cost: 20000, outcomes: [{ text: '"Bros, you be real one! Friday latest." 🙏', effect: { flag: 'lent-chinedu', rel: { chinedu: 10 } } }] },
      { label: 'Send ₦5,000 make e manage', cost: 5000, outcomes: [{ text: '"Thank you, e go help small." E sound disappointed.', effect: { flag: 'chinedu-done', rel: { chinedu: 3 } } }] },
      { label: '"Guy, I no get now"', outcomes: [{ text: '"Okay o." E cut call quick 😬', effect: { flag: 'chinedu-done', rel: { chinedu: -8 } } }] },
    ],
  },
  {
    id: 'chinedu-excuse',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '💬',
    title: 'Chinedu: "Small delay…"',
    text: '"Guy, salary never land o. Government money na wahala. Give me one more week abeg 🙏"',
    trigger: 'idle',
    weight: 40,
    cooldownHours: 9999,
    when: (c) => since(c, 'lent-chinedu') >= 3 && !has(c, 'chinedu-excuse') && free(c),
    choices: [
      { label: '"No wahala, take your time"', outcomes: [{ text: '"You too good, bros." 🫂', effect: { flag: 'chinedu-excuse', rel: { chinedu: 5 } } }] },
      { label: '"Guy, I need my money!"', outcomes: [{ text: '"I hear you. I no forget." E no happy 😐', effect: { flag: 'chinedu-excuse', rel: { chinedu: -5 } } }] },
    ],
  },
  {
    id: 'chinedu-again',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '😅',
    title: 'Chinedu wan borrow again',
    text: '"Bros, I know say I never pay the first one… but abeg add ₦10k. Last last. Na for my landlord."',
    trigger: 'idle',
    weight: 40,
    cooldownHours: 9999,
    when: (c) => since(c, 'chinedu-excuse') >= 2 && !has(c, 'chinedu-again') && free(c),
    choices: [
      { label: 'Send am ₦10,000', cost: 10000, outcomes: [{ text: '"I go never forget this one. Watch." 🙏', effect: { flag: ['chinedu-again', 'chinedu-trust'], rel: { chinedu: 8 } } }] },
      { label: '"Pay the first one first"', outcomes: [{ text: '"Fair. I go sort am." E sound shame.', effect: { flag: 'chinedu-again', rel: { chinedu: -5 } } }] },
    ],
  },
  {
    id: 'chinedu-payback',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '🤝',
    title: 'Chinedu don come through',
    text: '"Guy! Salary don land. And I get gist: my director need one sharp person for supply work. I don drop your name."',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 9999,
    when: (c) => since(c, 'chinedu-again') >= 3 && !has(c, 'chinedu-done') && free(c),
    choices: [
      {
        label: 'Collect money + the connection',
        when: (c) => has(c, 'chinedu-trust'),
        outcomes: [{ text: 'E send ₦30,000 back plus ₦15,000 "for your patience". Then e introduce you to Alhaji Sani 💰🦵', effect: { money: 45000, meet: 'alhaji', flag: 'chinedu-done', rel: { chinedu: 15 } } }],
      },
      {
        label: 'Collect your ₦20,000',
        when: (c) => !has(c, 'chinedu-trust'),
        outcomes: [{ text: 'E pay your ₦20k complete and push your CV for ministry 📄', effect: { money: 20000, cv: 1, flag: 'chinedu-done', rel: { chinedu: 5 } } }],
      },
    ],
  },

  // ---------------- Mama ----------------
  {
    id: 'mama-sick',
    caller: 'Mama 👵🏾',
    emoji: '📞',
    title: 'Mama dey call',
    text: '"My pikin, how you dey? BP dey worry me. Doctor say make I do test, ₦15,000. I no wan disturb you…"',
    trigger: 'idle',
    weight: 3,
    cooldownHours: 9999,
    when: (c) => c.day >= 4 && free(c) && !anyOf(c, 'mama-helped', 'mama-partial', 'mama-ignored'),
    choices: [
      { label: 'Send ₦15,000', cost: 15000, outcomes: [{ text: '"God bless you, my pikin. You go go far." 🙏', effect: { flag: 'mama-helped', needs: { social: 15, fun: 5 } } }] },
      { label: 'Send ₦5,000', cost: 5000, outcomes: [{ text: '"Thank you. I go add the rest from my contribution."', effect: { flag: 'mama-partial', needs: { social: 8 } } }] },
      { label: '"Mama, I no get now"', outcomes: [{ text: '"No wahala, my pikin. God dey." Her voice dey shake 😔', effect: { flag: 'mama-ignored', needs: { fun: -10 } } }] },
    ],
  },
  {
    id: 'mama-parcel',
    emoji: '📦',
    title: 'Parcel from Mama',
    text: 'Bus driver call you: "Your mama send load." Garri, beans, palm oil, dry fish… and one note: "Chop well, my pikin." 🥹',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 9999,
    when: (c) => since(c, 'mama-helped') >= 2 && !has(c, 'mama-done') && free(c),
    choices: [{ label: 'Call Mama to thank her', outcomes: [{ text: 'Una gist one hour. Your heart full 💛', effect: { pantry: 8, flag: 'mama-done', needs: { social: 25, fun: 15 } } }] }],
  },
  {
    id: 'mama-church',
    caller: 'Mama 👵🏾',
    emoji: '⛪',
    title: 'Mama get connection',
    text: '"My pikin, thank you for the money. My church sister daughter dey work for embassy for Maitama. I don give her your number."',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 9999,
    when: (c) => since(c, 'mama-partial') >= 2 && !has(c, 'mama-done') && free(c),
    choices: [{ label: 'Thank you, Mama!', outcomes: [{ text: 'Aisha text you: "Your mama na my mama. Come see me for embassy." 🛂', effect: { meet: 'aisha', flag: 'mama-done', needs: { social: 15 } } }] }],
  },
  {
    id: 'mama-hospital',
    caller: 'Aunty Ngozi',
    emoji: '🏥',
    title: 'Mama don enter hospital',
    text: 'Your aunty call: "Your mama collapse for market. She dey hospital now. Bill na ₦30,000."',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 9999,
    when: (c) => since(c, 'mama-ignored') >= 2 && !has(c, 'mama-done') && free(c),
    choices: [
      { label: 'Pay the bill', cost: 30000, outcomes: [{ text: 'Mama don stable. "I dey okay, my pikin." You promise yourself say next time you go answer 🙏', effect: { flag: 'mama-done', needs: { social: 10, fun: -10 } } }] },
      { label: 'Beg family to share the bill', outcomes: [{ text: 'Your uncles pay, but family WhatsApp group don dey talk about you 😔', effect: { money: -10000, flag: 'mama-done', needs: { social: -20, fun: -15 } } }] },
    ],
  },

  // ---------------- Garba's tip: an appointment ----------------
  {
    id: 'garba-tip',
    emoji: '🤫',
    title: 'Garba whisper you',
    text: '"Tomorrow morning, Director go interview people for contract staff. Come before 12. Dress well o, no come with slippers."',
    trigger: 'idle',
    weight: 8,
    cooldownHours: 9999,
    when: (c) => !!c.met?.includes('garba') && c.place === 'secretariat' && !anyOf(c, 'garba-appt', 'garba-done'),
    choices: [
      { label: '"I go dey there!"', outcomes: [{ text: '📌 Appointment: Federal Secretariat, tomorrow before 12 noon. No miss am!', effect: { flag: 'garba-appt', rel: { garba: 3 } } }] },
      { label: '"Tomorrow no go work for me"', outcomes: [{ text: '"Hmm. Opportunity no dey knock two times o."', effect: { flag: 'garba-done', rel: { garba: -3 } } }] },
    ],
  },
  {
    id: 'garba-interview',
    emoji: '👔',
    title: 'Director don come out',
    text: 'One man in agbada come out: "Who Garba send? Make you follow me."',
    trigger: 'idle',
    weight: 80,
    cooldownHours: 9999,
    when: (c) => since(c, 'garba-appt') === 1 && !has(c, 'garba-done') && c.place === 'secretariat' && c.hour >= 8 && c.hour < 12,
    choices: [
      {
        label: '"Na me, sir!"',
        outcomes: [
          { weight: (c) => 1 + (c.packaging ?? 0) / 15, text: 'Director like your packaging and confidence. "You fit start contract work immediately." 📄📄📄', effect: { cv: 3, flag: 'garba-done', rel: { garba: 10 } } },
          { weight: 1.5, text: 'Director look you from head to toe: "Come back when you serious." Your shirt don betray you 😩', effect: { flag: 'garba-done', needs: { fun: -15 } } },
        ],
      },
    ],
  },
  {
    id: 'garba-missed',
    caller: 'Mallam Garba 👳🏾‍♂️',
    emoji: '😤',
    title: 'You miss the appointment',
    text: 'Garba call: "You no come! I tell Director say my person serious. You don disgrace me."',
    trigger: 'idle',
    weight: 60,
    cooldownHours: 9999,
    when: (c) => since(c, 'garba-appt') >= 2 && !has(c, 'garba-done') && free(c),
    choices: [
      { label: '"Abeg, forgive me"', outcomes: [{ text: '"Hmm. Next time, I no go waste my mouth."', effect: { flag: 'garba-done', rel: { garba: -10 } } }] },
      { label: 'Send am ₦3,000 "for water"', cost: 3000, outcomes: [{ text: '"Okay. I go see wetin I fit do next time." 😏', effect: { flag: 'garba-done', rel: { garba: -2 } } }] },
    ],
  },

  // ---------------- Love ----------------
  {
    id: 'babe-hair',
    caller: 'Babe ❤️',
    emoji: '🥺',
    title: 'Babe dey call',
    text: '"Babe, I need ₦20k for small something before Sunday. You know say I love you 🥺"',
    trigger: 'idle',
    weight: 4,
    cooldownHours: 120,
    when: (c) => !!c.partner && free(c),
    choices: [
      { label: 'Send ₦20,000', cost: 20000, outcomes: [{ text: '"You be the best! 😍" E send you 10 kiss emoji.', effect: { partnerLove: 10 } }] },
      { label: '"Next week, babe"', outcomes: [{ text: '"Okay o." The "o" long 😐', effect: { partnerLove: -6 } }] },
      { label: '"Na ATM I be?"', outcomes: [{ text: 'E block you for 2 hours. Wahala 😤', effect: { partnerLove: -18, needs: { fun: -5 } } }] },
    ],
  },
  {
    id: 'love-jealous',
    emoji: '😱',
    title: 'Two of them don meet',
    text: 'You dey date two people at once… and dem just see each other for Jabi Lake Mall. Both of dem dey call you now.',
    trigger: 'idle',
    weight: 6,
    cooldownHours: 96,
    when: (c) => (c.dating ?? 0) >= 2 && free(c),
    choices: [
      { label: 'Tell the truth', outcomes: [{ text: 'One of dem respect your honesty. The other one don block you everywhere.', effect: { partnerLove: -10, needs: { social: -10 } } }] },
      { label: '"Na my cousin!"', outcomes: [{ weight: 1, text: 'E work… for now 😅', effect: { needs: { fun: -5 } } }, { weight: 2, text: 'Your "cousin" post screenshot for AbujaGram 💀', effect: { partnerLove: -25, followersPct: -5, needs: { social: -15 } } }] },
    ],
  },
  {
    id: 'fake-exposed',
    emoji: '🫣',
    title: 'Your fake life don burst',
    text: '"So the money wey you dey spend for VIP, na borrow? My friend see your account balance for POS." 😶',
    trigger: 'idle',
    weight: 8,
    cooldownHours: 96,
    when: (c) => !!c.fakeLife && (c.gap ?? 0) > 30 && free(c),
    choices: [
      { label: 'Confess everything', outcomes: [{ weight: 1, text: '"At least you honest." E go take time but e forgive you.', effect: { partnerLove: -10 } }, { weight: 1, text: '"I no fit date liar." E don waka 💔', effect: { partnerLove: -40, needs: { fun: -15 } } }] },
      { label: 'Form more big man', outcomes: [{ text: 'You transfer money you no get to prove point. Now you broke AND e still no believe you 😭', effect: { money: -20000, partnerLove: -20 } }] },
    ],
  },

  // ---------------- Phone calls ----------------
  {
    id: 'chinedu-mission',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '📍',
    title: '"Guy, where you dey?"',
    text: '"Come Secretariat tomorrow before 3pm. I get something for you. No tell anybody o."',
    trigger: 'idle',
    weight: 3,
    cooldownHours: 9999,
    when: (c) => !!c.met?.includes('chinedu') && has(c, 'chinedu-done') && !anyOf(c, 'chinedu-meet', 'chinedu-meet-done') && free(c),
    choices: [
      { label: '"I go dey there!"', outcomes: [{ text: '📌 Appointment: Federal Secretariat, tomorrow before 3pm.', effect: { flag: 'chinedu-meet' } }] },
      { label: '"Tomorrow no go work"', outcomes: [{ text: '"Okay, your loss o 😏"', effect: { flag: 'chinedu-meet-done', rel: { chinedu: -3 } } }] },
    ],
  },
  {
    id: 'chinedu-meet-show',
    emoji: '🎁',
    title: 'Chinedu don see you',
    text: 'Chinedu waka come out of ministry with envelope: "Our unit get small contract. I put your name. Na your share be this."',
    trigger: 'idle',
    weight: 80,
    cooldownHours: 9999,
    when: (c) => since(c, 'chinedu-meet') === 1 && !has(c, 'chinedu-meet-done') && c.place === 'secretariat' && c.hour >= 8 && c.hour < 15,
    choices: [{ label: 'Collect am 🙏', outcomes: [{ text: '₦25,000 plus Chinedu introduce you to Mrs. Okafor from HR 🤝', effect: { money: 25000, meet: 'okafor', flag: 'chinedu-meet-done', rel: { chinedu: 8 } } }] }],
  },
  {
    id: 'chinedu-meet-miss',
    caller: 'Chinedu 🧑🏾‍💼',
    emoji: '😑',
    title: '"You no come"',
    text: '"Guy, I wait you tire. The thing don go another person hand."',
    trigger: 'idle',
    weight: 60,
    cooldownHours: 9999,
    when: (c) => since(c, 'chinedu-meet') >= 2 && !has(c, 'chinedu-meet-done') && free(c),
    choices: [{ label: '"Abeg no vex"', outcomes: [{ text: '"Next time, show face."', effect: { flag: 'chinedu-meet-done', rel: { chinedu: -8 } } }] }],
  },
  {
    id: 'boss-call',
    caller: 'Your Oga (Director) 👔',
    emoji: '🗂️',
    title: '"Come office tomorrow"',
    text: '"We get report to finish for Minister. Come office tomorrow before 2pm. Overtime go dey."',
    trigger: 'idle',
    weight: 4,
    cooldownHours: 240,
    when: (c) => (c.grade ?? -1) >= 0 && c.hour >= 17 && c.hour < 21 && !has(c, 'boss-ot') && free(c),
    choices: [
      { label: '"Yes sir!"', outcomes: [{ text: '📌 Appointment: Federal Secretariat, tomorrow before 2pm.', effect: { flag: 'boss-ot' } }] },
      { label: '"Sir, I get family function"', outcomes: [{ weight: 2, text: '"Hmm. Okay." Your Oga no too happy.', effect: { needs: { fun: -5 } } }, { weight: 1, text: '"Na so you go dey do?" E don mark your name 😬', effect: { packaging: -2, needs: { fun: -10 } } }] },
    ],
  },
  {
    id: 'boss-ot-show',
    emoji: '💼',
    title: 'Overtime for Minister report',
    text: 'You and your Oga finish the report. "You try well. Na people like you dey get promotion." ',
    trigger: 'idle',
    weight: 80,
    cooldownHours: 9999,
    when: (c) => since(c, 'boss-ot') === 1 && c.place === 'secretariat' && c.hour >= 8 && c.hour < 14,
    choices: [{ label: '"Thank you sir!"', outcomes: [{ text: 'Overtime ₦20,000 and Oga don remember your face 😎', effect: { money: 20000, packaging: 3, minutes: 180, flag: 'boss-ot-done', needs: { energy: -15 } } }] }],
  },
  {
    id: 'boss-ot-miss',
    caller: 'Your Oga (Director) 👔',
    emoji: '😤',
    title: '"Where you dey?!"',
    text: '"I tell you say make you come! Minister report don late because of you."',
    trigger: 'idle',
    weight: 60,
    cooldownHours: 48,
    when: (c) => since(c, 'boss-ot') >= 2 && (c.flags?.['boss-ot-done'] ?? -1) < (c.flags?.['boss-ot'] ?? 0) && free(c),
    choices: [{ label: '"Sir, I sorry"', outcomes: [{ text: 'E hang up. Your name don dey bad book 📕', effect: { packaging: -3, flag: 'boss-ot-done', needs: { fun: -15 } } }] }],
  },
  {
    id: 'manager-call',
    caller: 'Your shop manager 🧑🏾‍🔧',
    emoji: '🔌',
    title: '"Oga, gen don spoil!"',
    text: '"Generator for shop don knock. Customers dey go back. Send ₦25,000 make we fix am today."',
    trigger: 'idle',
    weight: 3,
    cooldownHours: 168,
    when: (c) => (c.owned?.length ?? 0) >= 1 && free(c),
    choices: [
      { label: 'Send ₦25,000', cost: 25000, outcomes: [{ text: '"E don start! Thank you Oga." 💪🏾' }] },
      { label: '"Manage am today"', outcomes: [{ text: 'Shop no sell well today. You lose about ₦15,000 sales 😩', effect: { money: -15000 } }] },
    ],
  },
  {
    id: 'landlord-call',
    caller: 'Landlord 👴🏾',
    emoji: '🏠',
    title: '"Where my rent?"',
    text: '"My friend, I no see you for house. Where my rent? I dey give you till Friday."',
    trigger: 'idle',
    weight: 10,
    cooldownHours: 48,
    when: (c) => !!c.rentOverdue && c.place !== 'home' && c.place !== 'street',
    choices: [
      { label: '"Baba, I dey come pay"', outcomes: [{ text: '"I dey wait." Pay for 🏠 Rent app before e lock your door.' }] },
      { label: '"Abeg, add me few days"', outcomes: [{ weight: 1, text: '"Three days. Last warning!"', effect: { rentGraceDays: 3 } }, { weight: 1, text: '"No more story!" E hang up 😬', effect: { needs: { fun: -10 } } }] },
      { label: 'Switch off phone', outcomes: [{ text: 'Peace for now… e go reach house sha 🙈', effect: { needs: { fun: -5 } } }] },
    ],
  },
  {
    id: 'police-call',
    caller: 'Divisional Police HQ 🚔',
    emoji: '👮',
    title: '"Report to station tomorrow"',
    text: '"This na DPO office. Your name come up for one matter. Report to station for questioning."',
    trigger: 'idle',
    weight: 6,
    cooldownHours: 120,
    when: (c) => (c.heat ?? 0) >= 50 && (c.heat ?? 0) < 80 && free(c),
    choices: [
      { label: 'Go with Barrister Ade', cost: 15000, when: (c) => !!c.met?.includes('ade'), outcomes: [{ text: 'Barrister do the talking. Dem clear your name 📜', effect: { minutes: 120, heat: -25, rel: { ade: 3 } } }] },
      { label: 'Go alone', outcomes: [{ text: '3 hours of questions. Dem release you. Your heart dey beat 😮‍💨', effect: { minutes: 180, heat: -10, needs: { fun: -15, energy: -10 } } }] },
      { label: 'Ignore the call', outcomes: [{ text: 'Now dem don dey find you 🚨', effect: { heat: 15 } }] },
    ],
  },
  {
    id: 'partner-where',
    caller: 'Babe ❤️',
    emoji: '🎶',
    title: '"Where you dey this night?"',
    text: '"I dey hear music for background. Where you dey by this time?"',
    trigger: 'idle',
    weight: 8,
    cooldownHours: 72,
    when: (c) => !!c.partner && c.place === 'lounge' && c.hour >= 21,
    choices: [
      { label: 'Tell the truth', outcomes: [{ text: '"You for carry me along na!" Small vex.', effect: { partnerLove: -3 } }] },
      { label: '"I dey house, na TV"', outcomes: [{ weight: 1, text: '"Okay, goodnight." Phew 😮‍💨' }, { weight: 1, text: 'Your partner friend dey the same lounge 💀 Wahala don land.', effect: { partnerLove: -20, needs: { fun: -15 } } }] },
      { label: 'Invite am come join you', cost: 15000, outcomes: [{ text: 'Una dance till 2am 💃🏾🕺🏾', effect: { partnerLove: 10, needs: { fun: 15, social: 10 } } }] },
    ],
  },

  // ---------------- Festivals ----------------
  {
    id: 'sallah-ram',
    emoji: '🐏',
    title: 'Barka da Sallah!',
    text: 'Your neighbour Alhaji Musa knock with plate of rice and ram meat. "Na Sallah o! Chop well." Ram market dey hot for street too.',
    trigger: 'idle',
    weight: 40,
    cooldownHours: 200,
    when: (c) => c.festival === 'sallah' && free(c),
    choices: [
      { label: 'Collect with thanks 🙏', outcomes: [{ text: 'Ram meat sweet die! Your belle full, your heart full 🍛', effect: { pantry: 2, needs: { food: 30, social: 15 } } }] },
      { label: 'Buy your own ram, share with the compound', cost: 80000, outcomes: [{ text: 'Whole compound dey sing your name. "Our big man!" 🐏👑', effect: { packaging: 4, relAll: 3, needs: { social: 30, fun: 20 } } }] },
    ],
  },
  {
    id: 'christmas-family',
    caller: 'Family WhatsApp group 👨‍👩‍👧‍👦',
    emoji: '🎄',
    title: 'Christmas contribution',
    text: '"Merry Christmas everybody! Make all of us contribute ₦20k for village Christmas party. Abuja people, we dey look una o 👀"',
    trigger: 'idle',
    weight: 40,
    cooldownHours: 200,
    when: (c) => c.festival === 'christmas' && free(c),
    choices: [
      { label: 'Send ₦20,000', cost: 20000, outcomes: [{ text: 'Mama post your name for group with 10 🙏 emoji. You be good child!', effect: { needs: { social: 25, fun: 10 } } }] },
      { label: 'Go church carol service instead', outcomes: [{ text: 'Carols, candles, small chops after. Christmas feeling don enter 🕯️', effect: { minutes: 120, needs: { social: 20, fun: 15 } } }] },
      { label: '"Network bad" 📵', outcomes: [{ text: 'Family don dey call you "Abuja man wey forget home" 😬', effect: { needs: { social: -15 } } }] },
    ],
  },
  {
    id: 'independence-parade',
    emoji: '🇳🇬',
    title: 'Independence Day parade',
    text: 'Soldiers marching, jets flying over Eagle Square, everybody wear green-white-green.',
    trigger: 'idle',
    weight: 40,
    cooldownHours: 200,
    when: (c) => c.festival === 'independence' && c.place !== 'home' && c.hour >= 9 && c.hour < 17,
    choices: [
      { label: 'Join the crowd, wave flag 🇳🇬', outcomes: [{ text: 'You shout "One Nigeria!" till voice crack. Proud day 💚🤍💚', effect: { minutes: 90, needs: { fun: 25, social: 20, energy: -10 } } }] },
      { label: 'Stay inside, na public holiday', outcomes: [{ text: 'You sleep, watch the parade for TV. Rest na also patriotism 😴', effect: { needs: { energy: 15, fun: 5 } } }] },
    ],
  },
  {
    id: 'val-partner',
    emoji: '💘',
    title: "Val's Day expectations",
    text: 'Your partner don post "Some people go show their love today 👀" for status. Na you dem dey talk to.',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 200,
    when: (c) => c.festival === 'valentine' && !!c.partner && free(c),
    choices: [
      { label: 'Roses, chocolate & teddy bear', cost: 30000, outcomes: [{ text: 'E post am with "My person no dey disappoint 😍". Una relationship don level up 💕', effect: { partnerLove: 15, needs: { social: 15, fun: 10 } } }] },
      { label: 'Send sweet message only', outcomes: [{ weight: 1, text: '"Aww, thank you babe." E dey okay… small 😐', effect: { partnerLove: 2 } }, { weight: 1, text: '"Na only message?!" Wahala don start 😩', effect: { partnerLove: -12 } }] },
    ],
  },
  {
    id: 'val-single',
    emoji: '💔',
    title: "Val's Day for single people",
    text: 'Everybody for AbujaGram dey post bae, flowers and fine dinner. You dey look your screen.',
    trigger: 'idle',
    weight: 30,
    cooldownHours: 200,
    when: (c) => c.festival === 'valentine' && !c.partner && free(c),
    choices: [
      { label: 'Treat yourself to small chops', cost: 3000, outcomes: [{ text: 'Self-love na the best love 💅🏾', effect: { needs: { food: 20, fun: 15 } } }] },
      { label: 'Open Abuja Love app 👀', outcomes: [{ text: 'Maybe next Val go different 😏 Go swipe!', effect: { needs: { fun: 5 } } }] },
    ],
  },
  {
    id: 'crossover',
    emoji: '🎆',
    title: 'Crossover night!',
    text: 'Na New Year Eve. Where you go cross over?',
    trigger: 'idle',
    weight: 50,
    cooldownHours: 200,
    when: (c) => c.festival === 'newyear' && c.hour >= 18 && free(c),
    choices: [
      { label: 'Crossover service for church ⛪', outcomes: [{ text: 'Prayers, praise, fireworks at midnight. New year, new you 🙏', effect: { minutes: 240, needs: { social: 30, fun: 20, energy: -20 } } }] },
      { label: 'Party for the lounge 🍾', cost: 20000, outcomes: [{ text: '"10, 9, 8…" Bottles pop, everybody shout! You enter new year with style 🎆', effect: { minutes: 240, packaging: 2, needs: { fun: 45, social: 30, energy: -30 } } }] },
      { label: 'Sleep, na just another day', outcomes: [{ text: 'Knockout fireworks wake you at 12. Happy New Year anyway 😴🎆', effect: { needs: { energy: 20 } } }] },
    ],
  },
  {
    id: 'monthend-atm',
    emoji: '🏧',
    title: 'Month-end ATM queue',
    text: 'Salary don land for everybody. ATM queue long reach road, POS people dey charge double.',
    trigger: 'idle',
    weight: 15,
    cooldownHours: 200,
    when: (c) => c.festival === 'monthend' && c.place !== 'home' && c.hour >= 8 && c.hour < 18,
    choices: [
      { label: 'Join the ATM queue', outcomes: [{ text: 'One hour later, the ATM say "Unable to dispense cash" 😭', effect: { minutes: 60, needs: { fun: -15 } } }] },
      { label: 'Use POS (double charge)', cost: 1000, outcomes: [{ text: 'Quick and done. Time na money 💸' }] },
    ],
  },

  // ---------------- Scam call ----------------
  {
    id: 'scam-call',
    caller: '+234 809 *** ****',
    emoji: '☎️',
    title: 'Unknown number dey call',
    text: '"Hello, this is your bank. Your BVN don block. Send the OTP wey we just send you make we unblock am."',
    trigger: 'idle',
    weight: 2,
    cooldownHours: 240,
    when: (c) => c.money > 20000 && free(c),
    choices: [
      { label: 'Read out the OTP', outcomes: [{ text: 'Your account don drain! ₦20,000 don waka 😭 Bank go never call you for OTP.', effect: { money: -20000, needs: { fun: -25 } } }] },
      { label: '"Which bank? Which branch?"', outcomes: [{ text: 'Dem cut call. You sabi am 😎', effect: { needs: { fun: 10 } } }] },
    ],
  },
];
